import { parseBooleanVariable, parseNumber } from './utils';
import { getCIInfo } from './get-ci-info';

const { env } = process;

export const ENABLE_LOG             = parseBooleanVariable(env.TESTCAFE_DASHBOARD_DEVEXTREME_ENABLE_LOG);
export const TESTCAFE_DASHBOARD_URL = env.TESTCAFE_DASHBOARD_DEVEXTREME_URL || 'https://dashboard.testcafe.io';

export const NO_SCREENSHOT_UPLOAD = parseBooleanVariable(env.TESTCAFE_DASHBOARD_DEVEXTREME_NO_SCREENSHOT_UPLOAD);
export const NO_VIDEO_UPLOAD      = parseBooleanVariable(env.TESTCAFE_DASHBOARD_DEVEXTREME_NO_VIDEO_UPLOAD);

export const LAYOUT_TESTING_ENABLED = parseBooleanVariable(env.TESTCAFE_DASHBOARD_DEVEXTREME_LAYOUT_TESTING_ENABLED);
export const LT_SCREENSHOTS_DIR     = env.TESTCAFE_DASHBOARD_DEVEXTREME_LT_SCREENSHOTS_DIR;
export const LT_DESTINATION_DIR     = env.TESTCAFE_DASHBOARD_DEVEXTREME_LT_DESTINATION_DIR;
export const LT_COMPARER_BASE_DIR   = env.TESTCAFE_DASHBOARD_DEVEXTREME_LT_COMPARER_BASE_DIR;

export const TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN = env.TESTCAFE_DASHBOARD_DEVEXTREME_TOKEN;
export const TESTCAFE_DASHBOARD_BUILD_ID: string | undefined = env.TESTCAFE_DASHBOARD_DEVEXTREME_BUILD_ID;

export const REQUEST_RETRY_COUNT = parseNumber(env.TESTCAFE_DASHBOARD_DEVEXTREME_REQUEST_RETRY_COUNT) || 20;
export const RESPONSE_TIMEOUT    = parseNumber(env.TESTCAFE_DASHBOARD_DEVEXTREME_RESPONSE_TIMEOUT) || 30 * 1000;

export const CI_INFO = getCIInfo();
