export const CONCURRENT_ERROR_CODE          = 409;
export const SERVICE_UNAVAILABLE_ERROR_CODE = 503;

export const CLIENTTIMEOUT_ERROR_MSG = 'CLIENTTIMEOUT';

export const RETRY_ERROR_CODES = ['ECONNRESET', 'ETIMEDOUT', 'ECONNREFUSED', CLIENTTIMEOUT_ERROR_MSG];
