export const ENABLE_LOG             = process.env.ENABLE_LOG;
export const TESTCAFE_DASHBOARD_URL = process.env.TESTCAFE_DASHBOARD_URL;

export const TESTCAFE_DASHBOARD_AUTHORIZATION_TOKEN = process.env.TESTCAFE_DASHBOARD_AUTHORIZATION_TOKEN;
