export const ENABLE_LOG             = process.env.ENABLE_LOG;
export const TESTCAFE_DASHBOARD_URL = process.env.TESTCAFE_DASHBOARD_URL;

export const ENABLE_SCREENSHOTS_UPLOAD = !!process.env.ENABLE_SCREENSHOTS_UPLOAD;

export const TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN = process.env.TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN;
