name: Audit

on:
  pull_request:
    branches: [ alpha ]

jobs:
  devDependencies:
    name: Audit Dev Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Show ip
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Yarn audit
        run: yarn audit
  yarnDependencies:
    name: Yarn - Audit Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Show ip
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Upgrade lockfile
        run: yarn upgrade
      - name: Yarn audit Dependencies
        run: yarn audit --groups dependencies
  npmDependencies:
    name: NPM - Audit Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Show ip
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: npm install
        run: npm install
      - name: NPM audit Dependencies
        run: npm audit --omit=dev
