  
name: Npm audit

on:
  pull_request_target:
    branches: [ master ]

env:
  VM_MEMORY: 2600
  VM_CPU: 2


jobs:
  run:
    runs-on: farm
    strategy:
      matrix:
        oses: [UBUNTU]
    env:
      VM_IMAGE: ${{ matrix.oses }}

    steps:
      - name: Show ip
        run: ip addr show
      - name: Clone
        uses: ./../../checkout
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'http://npmproxy:4873'
      - name: npm 
        run: npm audit
