name: Npm audit

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ master ]

jobs:
  run:
    runs-on: shr-ubuntu-m5a-instance-cpu2ram8
    timeout-minutes: 30

    steps:
      - name: Show ip
        run: ip addr show
      - name: Checkout PR Head
        if: ${{ github.event.pull_request != null }}
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
      - name: Checkout Base Branch
        if: ${{ github.event.pull_request == null }}
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: npm audit
        run: npm audit
