name: Npm audit

on:
  pull_request:
    branches: [ alpha ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Show ip
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: npm audit
        run: npm audit
