name: Unit tests

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ master ]

jobs:
  run:
    runs-on: farm
    strategy:
      matrix:
        oses: [UBUNTU]
    env:
      VM_IMAGE: ${{ matrix.oses }}

    steps:
      - name: Show ip
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn
        run: npm install -g yarn
      - name: yarn install
        run: yarn install
      - name: Run Tests
        run: yarn run test
