name: Unit tests

on:
  pull_request:
    branches: [ alpha ]

jobs:
  run:
    name: ${{ matrix.args.name }}
    runs-on: ${{ matrix.args.machineName }}
    strategy:
      matrix:
        args: [
          { name: "Ubuntu", machineName: "ubuntu-latest" },
          { name: "Windows", machineName: "windows-latest" }
        ]

    steps:
      - name: Show ip
        if: ${{ matrix.name == 'Ubuntu' }}
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: Run Tests
        run: npm run test
