name: Unit tests

on:
  pull_request_target:
    branches: [ master ]

env:
  VM_MEMORY: 2600
  VM_CPU: 1

jobs:
  run:
    runs-on: farm
    strategy:
      matrix:
        oses: [UBUNTU]
    env:
      VM_IMAGE: ${{ matrix.oses }}

    steps:
      - name: Show ip
        run: ip addr show
      - name: Clone
        uses: ./../../checkout
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'http://npmproxy:4873'
      - name: npm install
        run: npm install
      - name: Run Tests
        run: npm run test
