name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  run:
    name: ${{ matrix.args.name }}
    runs-on: ${{ matrix.args.machineName }}
    strategy:
      matrix:
        args: [
          { name: "Ubuntu", machineName: "ubuntu-latest" },
          { name: "Windows", machineName: "windows-latest" }
        ]

    steps:
      - name: Show ip
        if: ${{ matrix.name == 'Ubuntu' }}
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn
        run: npm install -g yarn
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn run test
